application: dropchatapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /app.js
  static_files: app.js
  upload: app.js
  login: required

- url: /views
  static_dir: views
  login: required

- url: /js
  static_dir: js
  login: required

- url: /css
  static_dir: css
  login: required

- url: /images
  static_dir: images
  login: required

- url: /themes
  static_dir: themes
  login: required

- url: /api/.*
  script: api.app
  login: required

- url: /_ah/channel/.*
  script: api.app

- url: /
  static_files: app.html
  upload: app.html
  login: required
  http_headers:
    Access-Control-Allow-Origin: "*"

libraries:
- name: webapp2
  version: "latest"

inbound_services:
- channel_presence